### ISSUE TITLE
Request: allow web clipper to be used independently with other open source apps

### ISSUE THREAD

**Issue by sunjam** [tagspaces/browser-extensions#1]
It would be awesome to use the web clipper with other projects such as [Joplin issue #135](https://github.com/laurent22/joplin/issues/135) as an independent app thatworks with any similar webdav app [as mentioned in issue #597](https://github.com/tagspaces/tagspaces/issues/597).

**Comment by uggrock** [comment]
The web clipper is actually very loosely coupled to the desktop version of TagSpaces, with features such as using the file name for tagging. The outputs of the web clipper are plain files in HTML, MHTML, PNG or URL format which can be used with other project supporting these formats. So from my point view, it can be used with other projects...

**Comment by sunjam** [comment]
That is fantastic news!  Do you have any documentation that could be shared
with other devs?
