### ISSUE TITLE
SAVE COMPLETE PAGE defaults to "txt" extension rather than "mhtml"

### ISSUE THREAD

**Issue by jskksj** [tagspaces/browser-extensions#17]
I am having to manually change the extension to mhtml when I use the web clipper.

This is in the brave.com browser based on chrome.

**Comment by uggrock** [comment]
It appears that something was changed in Chrome/Chromium recently, the some behavior is reproducible also there. We have no idea for now how can we fix this....

**Comment by uggrock** [comment]
Fixed in version 3.1.1.
