### ISSUE TITLE
Use sidecar files for tagging in the webclipper

### ISSUE THREAD

**Issue by edgartaor** [tagspaces/browser-extensions#31]
It is possible to create sidecar files with the web clipper? I can't find any option for that.
Optionally, the desktop app could read the tags from the filename, remove it and create the tag files.

I would prefer the sidecar files were created by the web clipper directly if possible.

**Having tags in sidecar files and tags in filenames it too inconsistent .** 

Is there any workaround for this?

**Comment by uggrock** [comment]
No, downloading two files is unfortunately technically not possible.
